name: CI

on: [pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
        flags: [-ggdb3, -O3]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      env:
        CC: ${{ matrix.compiler }}
      run: |
        make install
        make build
